### ISSUE TITLE
Installation issue on Home Assistant Node-RED addon

### ISSUE THREAD

**Issue by wobondar** [friendsincode/node-red-hap-controller#4]
Node-RED: v3.1.0
NodeJS: 18.17.1
Home Assistant: 2023.9.3
Node-RED add-on: v14.5.0

```
-----------------------------------------------------------
2023-09-27T19:59:46.777Z Install : @friendsincode/node-red-hap-controller 0.0.8

2023-09-27T19:59:46.941Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict @friendsincode/node-red-hap-controller@0.0.8
2023-09-27T19:59:49.575Z [err] npm
2023-09-27T19:59:49.578Z [err]  WARN 
2023-09-27T19:59:49.578Z [err] config production Use `--omit=dev` instead.
2023-09-27T20:00:09.402Z [err] npm
2023-09-27T20:00:09.402Z [err]  ERR! code 1
2023-09-27T20:00:09.404Z [err] npm ERR! path
2023-09-27T20:00:09.404Z [err]  /config/node-red/node_modules/@abandonware/noble
2023-09-27T20:00:09.414Z [err] npm ERR!
2023-09-27T20:00:09.415Z [err]  command failed
2023-09-27T20:00:09.415Z [err] npm ERR! command sh -c node-gyp-build
2023-09-27T20:00:09.417Z [err] npm ERR! gyp info it worked if it ends with ok
2023-09-27T20:00:09.417Z [err] npm ERR! gyp info using node-gyp@9.3.1
2023-09-27T20:00:09.417Z [err] npm ERR! gyp info using node@18.17.1 | linux | arm64
2023-09-27T20:00:09.417Z [err] npm ERR! gyp ERR! find Python 
2023-09-27T20:00:09.417Z [err] npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2023-09-27T20:00:09.417Z [err] npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2023-09-27T20:00:09.417Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python 
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! find Python 
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! configure error 
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2023-09-27T20:00:09.422Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2023-09-27T20:00:09.422Z [err] npm ERR!
2023-09-27T20:00:09.424Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! System Linux 6.1.21-v8
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@abandonware/noble
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! node -v v18.17.1
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.1
2023-09-27T20:00:09.424Z [err] npm ERR! gyp ERR! not ok
2023-09-27T20:00:09.433Z [err] 
2023-09-27T20:00:09.433Z [err] npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-27T19_59_49_436Z-debug-0.log
2023-09-27T20:00:09.485Z rc=1
```

**Comment by wobondar** [comment]
Since there doesn’t seem to be any interest or response regarding this issue, I will close it.
